//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypeMaster.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TypeMaster.Properties.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string MenuButton0 {
            get {
                return ResourceManager.GetString("MenuButton0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Random.
        /// </summary>
        internal static string MenuButton1 {
            get {
                return ResourceManager.GetString("MenuButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoreboard.
        /// </summary>
        internal static string MenuButton2 {
            get {
                return ResourceManager.GetString("MenuButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MenuButton3 {
            get {
                return ResourceManager.GetString("MenuButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string MenuButton4 {
            get {
                return ResourceManager.GetString("MenuButton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page ID.
        /// </summary>
        internal static string ScoreboardHeader0 {
            get {
                return ResourceManager.GetString("ScoreboardHeader0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ScoreboardHeader1 {
            get {
                return ResourceManager.GetString("ScoreboardHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words Per Minute.
        /// </summary>
        internal static string ScoreboardHeader2 {
            get {
                return ResourceManager.GetString("ScoreboardHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds Spent.
        /// </summary>
        internal static string ScoreboardHeader3 {
            get {
                return ResourceManager.GetString("ScoreboardHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words Count.
        /// </summary>
        internal static string ScoreboardHeader4 {
            get {
                return ResourceManager.GetString("ScoreboardHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Length.
        /// </summary>
        internal static string ScoreboardHeader5 {
            get {
                return ResourceManager.GetString("ScoreboardHeader5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Language.
        /// </summary>
        internal static string ScoreboardHeader6 {
            get {
                return ResourceManager.GetString("ScoreboardHeader6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for wiki articles and select them.
        /// </summary>
        internal static string SearchArticlesTextBlock {
            get {
                return ResourceManager.GetString("SearchArticlesTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        internal static string TextLength0 {
            get {
                return ResourceManager.GetString("TextLength0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string TextLength1 {
            get {
                return ResourceManager.GetString("TextLength1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        internal static string TextLength2 {
            get {
                return ResourceManager.GetString("TextLength2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time.
        /// </summary>
        internal static string TypeTestElapsedTime {
            get {
                return ResourceManager.GetString("TypeTestElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string TypeTestLoading {
            get {
                return ResourceManager.GetString("TypeTestLoading", resourceCulture);
            }
        }
    }
}
